services:
  redis:
    image: redis:7-alpine
    volumes:
      - redis_data:/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      - moon_golem_network

  filesdb:
    image: moonplkr/filesdb:latest
    ports:
      - "3003:3003"
    env_file: .env.local
    environment:
      - NODE_ENV=production
      - PORT=3003
      - ARKIV_CHAIN_ID=60138453025
      - ARKIV_RPC_URL=https://kaolin.hoodi.arkiv.network/rpc
      - ARKIV_WS_URL=wss://kaolin.hoodi.arkiv.network/rpc/ws
      - STORAGE_MODE=arkiv
      - BLOCKCHAIN_TIMEOUT=300000
      - REDIS_URL=redis://redis:6379
    secrets:
      - arkiv_private_key
    volumes:
      - ./data:/usr/src/app/data
    depends_on:
      - redis
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3003/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - moon_golem_network
    labels:
      # Main domain through Cloudflare (for regular requests)
      - "traefik.enable=true"
      - "traefik.http.routers.filesdb-main.rule=Host(`filedb.online`)"
      - "traefik.http.routers.filesdb-main.entrypoints=websecure"
      - "traefik.http.routers.filesdb-main.tls.certresolver=letsencrypt"
      - "traefik.http.routers.filesdb-main.service=filesdb-service"

      # Upload subdomain without Cloudflare (direct to server)
      - "traefik.http.routers.filesdb-upload.rule=Host(`upload.filedb.online`)"
      - "traefik.http.routers.filesdb-upload.entrypoints=websecure"
      - "traefik.http.routers.filesdb-upload.tls.certresolver=letsencrypt"
      - "traefik.http.routers.filesdb-upload.service=filesdb-service"

      # Service definition
      - "traefik.http.services.filesdb-service.loadbalancer.server.port=3003"

      # Increase timeout for upload domain
      - "traefik.http.routers.filesdb-upload.middlewares=upload-timeout"
      - "traefik.http.middlewares.upload-timeout.buffering.maxRequestBodyBytes=0"
      - "traefik.http.services.filesdb-service.loadbalancer.responseForwarding.flushInterval=100ms"

secrets:
  arkiv_private_key:
    file: ./secrets/arkiv_private_key.txt

volumes:
  redis_data:

networks:
  moon_golem_network:
    external: true