name: Smoke Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
    # Run smoke tests every 4 hours
    - cron: '0 */4 * * *'
  workflow_dispatch:
    # Allow manual trigger

jobs:
  smoke-tests-production:
    name: Production Smoke Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Install dependencies
        run: bun install

      - name: Run smoke tests against production
        run: TEST_BASE_URL=https://filedb.online bun test tests/smoke --timeout 20000
        continue-on-error: true
        id: smoke-tests

      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: smoke-test-results
          path: |
            *.log
            test-results/

      - name: Notify on failure
        if: failure() && steps.smoke-tests.outcome == 'failure'
        uses: actions/github-script@v7
        with:
          script: |
            github.rest.issues.create({
              owner: context.repo.owner,
              repo: context.repo.repo,
              title: '🔥 Production Smoke Tests Failed',
              body: `Production smoke tests failed at ${new Date().toISOString()}\n\n` +
                    `**Workflow:** ${{ github.workflow }}\n` +
                    `**Run:** ${{ github.run_id }}\n\n` +
                    `Please investigate: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}`,
              labels: ['bug', 'smoke-test', 'production']
            })
